download_providers:
  - host: news.newsgroup.ninja
    insecure_ssl: false
    is_backup_provider: false
    max_connection_idle_time_in_seconds: 2400
    max_connection_ttl_in_seconds: 2400
    max_connections: 9
    password: 7abdJ!PhuXyFxz7
    port: 80
    tls: true
    username: laris11
upload_providers:
  - host: localhost
    join_group: true
    max_connections: 20
    password: null
    port: 1199
    tls: false
    username: null
